# Generated by Django 3.1.2 on 2020-10-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='roomType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='hotelImages/')),
                ('facility', models.CharField(max_length=300)),
                ('capacity', models.CharField(max_length=20)),
                ('beds', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='roomImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='hotelImages/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_admin.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='hotelRooms',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_admin.roomtype')),
            ],
        ),
    ]
