# Generated by Django 3.1.2 on 2020-10-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
