# Generated by Django 3.1.2 on 2020-10-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0003_bookingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='checkin_time',
            field=models.TimeField(default=(12, 0, 0)),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='checkout_time',
            field=models.TimeField(default=(11, 0, 0)),
        ),
    ]
