# Generated by Django 3.1.2 on 2020-10-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0004_auto_20201027_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='checkin_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='checkout_time',
            field=models.TimeField(default='11:00'),
        ),
    ]
