# Generated by Django 3.1.2 on 2020-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0005_auto_20201027_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkin_time', models.TimeField(default='12:00')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='checkout_time',
        ),
    ]
