# Generated by Django 3.1.2 on 2020-10-28 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0006_auto_20201028_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
