# Generated by Django 3.1.2 on 2020-10-28 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0007_auto_20201028_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='checkin_time',
        ),
    ]
