# Generated by Django 3.1.2 on 2020-10-28 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0008_remove_demo_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
