# Generated by Django 3.1.2 on 2020-10-28 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMSapp', '0009_demo_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='checkout_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
