# Generated by Django 3.1.2 on 2020-10-30 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='bookedRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateTimeField(default=datetime.time(12, 0))),
                ('checkout_date', models.DateTimeField(default=datetime.time(11, 0))),
                ('status', models.CharField(default='Confirm', max_length=40)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_admin.hotelrooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.user')),
            ],
        ),
    ]
