# Generated by Django 3.1.2 on 2020-11-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20201103_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedrooms',
            name='checkin_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='bookedrooms',
            name='checkout_time',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='checkin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedrooms',
            name='checkout_date',
            field=models.DateField(),
        ),
    ]
